# Change these first
owner: developerciar # Your GitHub organization or username, where this repository lives
repo: st_apps # The name of this repository

sites:
  - name: Ceres
    url: http://erp.clusterciar.com.ar
  - name: N1
    url: http://n1.clusterciar.com.ar
  - name: N2
    url: http://n2.clusterciar.com.ar
  - name: wa
    url: http://ws.clusterciar.com.ar
    
status-website:
  baseUrl: /st_apps # where "repo" is your repository name
  name: Clusterciar Apps
#status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  #logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  #name: Upptime
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  #navbar:
  #  - title: Status
  #    href: /
  #  - title: GitHub
  #    href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
